name: Deploy server
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd chat-app
            export REDIS_URL=${{ secrets.REDIS_URL }}
            export CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            cd server
            npm install -g pnpm
            export NVM_DIR="$HOME/.nvm"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 18.17.0 && nvm use 18.17.0
            pnpm install
            pnpm build
            docker-compose down
            docker-compose up --project-name chat-api up -d --build
